apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sandbox-mommy.labels" . | nindent 4 }}
    {{ include "sandbox-controller.componentLabel" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sandbox-controller-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: sandbox-controller
    namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sandbox-mommy.labels" . | nindent 4 }}
    {{ include "sandbox-api.componentLabel" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sandbox-api-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: sandbox-api
    namespace: {{ .Release.Namespace }}

