{{- $ca := genCA "sandbox-controller CA" 365 }}
{{- $CN := (include "sandbox-controller.serviceFQDN" .) }}
{{- $cert := genSignedCert $CN (list "127.0.0.1") (list "localhost" $CN) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: sandbox-controller-tls
  labels:
    {{- include "sandbox-mommy.labels" . | nindent 4 }}
    {{ include "sandbox-controller.componentLabel" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    {{ include "sandbox-mommy.labels" . | nindent 4 }}
    {{ include "sandbox-controller.componentLabel" . | nindent 4 }}
  name: "sandbox-controller-admission-webhook"
webhooks:
  - name: "sandbox.sandbox.io.validate"
    rules:
      - apiGroups:   ["sandbox.io"]
        apiVersions: ["v1alpha1"]
        operations:  ["CREATE"]
        resources:   ["sandboxes"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: sandbox-controller
        path: /validate-sandbox-io-v1alpha1-sandbox
        port: 443
      caBundle: |
        {{ $ca.Cert | b64enc }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
  - name: "sandboxtemplate.sandbox.io.validate"
    rules:
      - apiGroups:   ["sandbox.io"]
        apiVersions: ["v1alpha1"]
        operations:  ["CREATE"]
        resources:   ["sandboxtemplates"]
        scope:       "Cluster"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: sandbox-controller
        path: /validate-sandbox-io-v1alpha1-sandboxtemplate
        port: 443
      caBundle: |
        {{ $ca.Cert | b64enc }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    {{ include "sandbox-mommy.labels" . | nindent 4 }}
    {{ include "sandbox-controller.componentLabel" . | nindent 4 }}
  name: "sandbox-controller-mutating-webhook"
webhooks:
  - name: "sandbox.sandbox.io.default"
    rules:
      - apiGroups:   ["sandbox.io"]
        apiVersions: ["v1alpha1"]
        operations:  ["CREATE"]
        resources:   ["sandboxes"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: sandbox-controller
        path: /mutate-sandbox-io-v1alpha1-sandbox
        port: 443
      caBundle: |
        {{ $ca.Cert | b64enc }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: Never
    matchPolicy: Exact